
services:
  db:
    image: postgres:16-alpine
    container_name: banking_db_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: bankingP@ssw0rdAet75
      POSTGRES_DB: banking_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: